Allow user to overwrite line-length flags for gfortran linter
fortran-lang/vscode-fortran-support pull request #924
Opened 2023-06-21 09:54 UTC by albertziegenhagel

Currently, the code appends `-ffree-line-length-none` and `-ffixed-line-length-none` by default to the argument list when invoking `gfortran` as linter. While it is possible to overwrite the line-length by setting `fortls.maxLineLength`, this does only allow to set the same value for both, free-form as well es fixed-form Fortran code. What I need is to keep the common default values (72 for fixed-form and 132 (or none) for free-form Fortran).

A comment in the code at [src/lint/provider.ts#L554](https://github.com/fortran-lang/vscode-fortran-support/blob/fc0419dd3d2db8dca469891a7d65adac1f1381a3/src/lint/provider.ts#L554) states that it should be possible to overwrite those defaults by setting them explicitly in `extraArgs`, but this does not currently work. The reason is that the default arguments are pushed to the argument list **after** the user provided arguments. Hence the defaults will always overwrite the user provided flags.

The proposed fix here is to put the default arguments **before** the user provided flags. This way, if a user puts `-ffixed-line-length-X` or `-ffree-line-length-X` into `extraArgs`, these will always overwrite the defaults.

If there is any other preferred way to solve this issue, just let me know and I will update the PR. I choose the current approach because it seemed to be the least invasive change and the comment in the code made me feel that this was actually the desired behavior in the first place.

2023-06-21 22:58 UTC, gnikit requested changes
That looks good, nice catch. Can you also update the CHANGELOG and add a comment about why we use `unshift` there.

I think this warrants a more robust fix in the future, but it looks good for now.

2023-06-22 06:35 UTC, albertziegenhagel commented
> Can you also update the CHANGELOG and add a comment in the source-code about why we use `unshift` there.

Done.

> I think this warrants a more robust fix in the future, but it looks good for now.

Yes, that was my impression as well. If you have any specific idea how this should be handled, let me know and I would be glad to create a subsequent PR.

2023-06-22 11:45 UTC, gnikit commented
Thanks @albertziegenhagel for the PR.

The more robust way will be to add a separate diagnostic option in fortls, propagate that option to vscode, and if an option that overrides the fortls line length diagnostics (, or linter defaults) is specified in the `extraArgs` then replace that option.

2023-06-22 11:45 UTC, gnikit approved these changes

2023-06-22 11:45 UTC, merged